sellgame/cart/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

sellgame/catalog/urls.py
from django.urls import path, re_path
from catalog import views
from sellgame import settings
from django.conf.urls.static import static


app_name = 'catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellgame/drf/urls.py
from django.urls import path, re_path, include
from drf.views import *

app_name = 'drf'
urlpatterns = [
    path('v1/news/', NewsAPIList.as_view()),
    path('v1/drf-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('v1/news/<int:pk>/', NewsAPIUpdate.as_view()),
    path('v1/newsdelete/<int:pk>/', NewsAPIDestroy.as_view()),
    path('/v1/auth/', include('djoser.urls')),  # new
    re_path(r'^auth/', include('djoser.urls.authtoken')),  # new
    path('v1/cat/', CatalogAPIList.as_view()),
    path('v1/cat/<int:pk>/', CatalogAPIUpdate.as_view()),
    path('v1/catdestroy/<int:pk>/', CatalogAPIDestroy.as_view()),
]

sellgame/sellgame/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from news import views
from sellgame import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('catalog/', include('catalog.urls', namespace='shop')),
    path('orders/', include('order.urls', namespace='order')),
    path('account/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellgame/catalog/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name', ]

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name

class NameGame(models.Model):
    name = models.TextField(max_length=255, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Название игры'
        verbose_name_plural = 'Названия игр'


class KeyGame(models.Model):
    name = models.ForeignKey(NameGame, on_delete=models.PROTECT, verbose_name='Название')
    key = models.TextField(max_length=30, verbose_name="Ключ")

    class Meta:
        verbose_name = 'Ключ игры'
        verbose_name_plural = 'Ключи игр'
        ordering = ['name', ]


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Жанр')
    name = models.TextField(verbose_name='Название игры')
    connect = models.ForeignKey(NameGame, on_delete=models.PROTECT, verbose_name='Связь с игрой')
    description = models.TextField(verbose_name='Описание')
    photo = models.ImageField(upload_to="game/%Y/%m/%d/", verbose_name='Фото')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.IntegerField(verbose_name='Осталось')
    Publisher = models.TextField(verbose_name='Издатель')
    Developer = models.TextField(verbose_name='Разработчик')
    release = models.DateField(verbose_name="Дата выхода")
    is_published = models.BooleanField(default=True, verbose_name='Публикация')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    class Meta:
        verbose_name = 'Каталог'
        verbose_name_plural = 'Каталог'
        ordering = ['name', 'time_create']
        index_together = (('name', 'slug'),)

    def __str__(self):
        return self.name

sellgame/catalog/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from cart.forms import CartAddProductForm
from .models import *


def product_list(request, category_slug=None):
    name_key = NameGame.objects.all()
    for name in name_key:  # Количество ключей в каталоге
        q_name = KeyGame.objects.filter(name=name).count()
        Product.objects.filter(connect=name.id).update(stock=q_name)

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(is_published=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {
        "category": category,
        "categories": categories,
        "products": products
    }
    return render(request, 'catalog/list.html', context=context)


# def show_post(request, post_id):
#     return HttpResponse(f"Отображение игры с id = {post_id}")

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, is_published=True)
    cart_product_form = CartAddProductForm()

    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'catalog/detail.html', context=context)

sellgame/templates/catalog/catalog.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Новости | SellGame</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>

<!-- Навигационное меню -->
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="../../catalog">SellGame</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Аккаунт</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">О нас</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</nav>
<!-- Навигационное меню -->

<div class="page-wrapper">
    <div class="left-panel-wrapper">
        <div class="left-panel">

        </div>
    </div>

    <div class="content-wrapper">
        <div class="content">
            {% for cat in cat %}
            <table class="iksweb">
                <tbody>
                <tr>
                    <td rowspan="2"><img src="{{cat.photo.url}}" width="150"></td>
                    <td colspan="2">{{cat.name}}</td>
                </tr>
                <tr>
                    <td width="100">{{cat.release.year}}</td>
                    <td>Цена {{cat.price}}</td>
                </tr>
                </tbody>
            </table>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ cat.get_absolute_url }}'"
                    name='mybtn1'>Страница игры
            </button>

            <hr>
            <br>
            {% endfor %}
        </div>
    </div>

    <div class="right-panel-wrapper">
        <div class="right-panel">

        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
</html>

sellgame/templates/catalog/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.title }}{% else %}Игры | SellGame{% endif %}
{% endblock %}
{% block content %}

<div class="page-wrapper">
    <div class="content-wrapper">
        <div class="content">
            <img src="{% if product.photo %}{{ product.photo.url }}{% else %}{% static ' img/no_image.png' %}{% endif %}"
                 width="150">
            <h1>{{ product.name }}</h1>
            <h3><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h3>
            <p class="price"> &#x20bd {{ product.price }}</p>
            <p>Всего осталось: {{ product.stock }} ключа</p>
            {{ product.description|linebreaks }}
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину">
            </form>
        </div>
    </div>
</div>
{% endblock %}

sellgame/templates/catalog/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Каталог | SellGame{% endif %}
{% endblock %}

{% block content %}
<div class="page-wrapper">
    <div class="left-panel-wrapper">
        <div class="left-panel">
            <h3>Категории</h3>
            <ul>
                <li {% if not category %}class="selected" {% endif %}>
                    <a href="{% url 'shop:product_list' %}">All</a>
                </li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="content-wrapper">
        <div class="content">
            <h1>{% if category %}{{ category.name }}{% else %}Игры{% endif %}</h1>
            {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.photo %}{{ product.photo.url }}{% else %}{% static ' img/no_image.png' %}{% endif %}"
                         width="150">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                <p>&#x20bd {{ product.price }}</p>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="right-panel-wrapper">
        <div class="right-panel">

        </div>
    </div>
</div>
</div>
{% endblock %}