sellgame/cart/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

sellgame/catalog/urls.py
from django.urls import path, re_path
from catalog import views
from sellgame import settings
from django.conf.urls.static import static


app_name = 'catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellgame/drf/urls.py
from django.urls import path, re_path, include
from drf.views import *

app_name = 'drf'
urlpatterns = [
    path('v1/news/', NewsAPIList.as_view()),
    path('v1/drf-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('v1/news/<int:pk>/', NewsAPIUpdate.as_view()),
    path('v1/newsdelete/<int:pk>/', NewsAPIDestroy.as_view()),
    path('/v1/auth/', include('djoser.urls')),  # new
    re_path(r'^auth/', include('djoser.urls.authtoken')),  # new
    path('v1/cat/', CatalogAPIList.as_view()),
    path('v1/cat/<int:pk>/', CatalogAPIUpdate.as_view()),
    path('v1/catdestroy/<int:pk>/', CatalogAPIDestroy.as_view()),
]

sellgame/order/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'order'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

sellgame/sellgame/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from news import views
from sellgame import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('catalog/', include('catalog.urls', namespace='shop')),
    path('orders/', include('order.urls', namespace='order')),
    path('account/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellgame/cart/models.py
from django.db import models

# Create your models here.

sellgame/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 3)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,
                                      label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

sellgame/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

sellgame/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Корзина | SellGame
{% endblock %}
{% block content %}
<div class="page-wrapper">
    <div class="left-panel-wrapper">
        <div class="left-panel">

        </div>
    </div>
    <div class="content-wrapper">
        <div class="content">
            <h1>Корзина</h1>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Изображение</th>
                    <th scope="col">Игра</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Удалить</th>
                    <th scope="col">Цена игры</th>
                    <th scope="col">Общая цена</th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.photo %}{{ product.photo.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
                                 width="100">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">Удалить</a></td>
                    <td class="num"> &#x20bd {{ item.price }}</td>
                    <td class="num"> &#x20bd {{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>Всего</td>
                    <td colspan="4"></td>
                    <td class="num"> &#x20bd {{ cart.get_total_price }}</td>
                </tr>
                </tbody>
            </table>
            <p class="text-right">
                <a href="{% url 'shop:product_list' %}" class="button light">Продолжить покупки</a>
                {% if cart.get_total_price > 0 %}
                <a href="{% url 'order:order_create' %}" class="button">Создать заказ</a>
                {% endif %}
            </p>
        </div>
    </div>
    <div class="right-panel-wrapper">
        <div class="right-panel">

        </div>
    </div>
</div>
{% endblock %}